### ISSUE TITLE
Triggering events before dom is ready

### ISSUE THREAD

**Issue by thomhos** [JFusco/es6-event-emitter#4]
Hello,

I'm wondering if it's possible to trigger an event on the constructor, or a method that is called immediately after the class is instantiated. 

I'm trying to do something like this;

```
class Bla extends Emitter {
  constructor() {
    super()
    this.trigger('bla:initialised')
}
}
```

I notice this event doesn't fire, probably because it hasn't fully loaded or something. How would you do something like this?

Cheers

**Comment by JFusco** [comment]
Hi @thomhos 

The reason it's not being called is because you have to subscribe to the event **before** calling an action (or triggering).  I could create some type of queue layer to handle this type of instance you provided. To get around it right now you could just have a method like `this.viewInitialized()` and have that trigger your 'bla:initialised' event.

See the home page of the repo for the example. Notice that we subscribe before calling `component.someAction();`

If you need help with this, i'll be glad to give you a more in depth example.  I'll also work on a solution for this.

Thanks

**Comment by thomhos** [comment]
Hi,

I think I get it. The constructor method is probably called before I can subscribe to it. I think there are a few ways to achieve getting an init event triggered, what would your preferred solution be?

I'm thinking I can either do what you suggest; have the constructor call a method that fires the init event. In the meantime I can subscribe immediately after initialising the class. I'm not sure if it will always be on time thoug?

Another option might be to instantiate the class, but initialise it externally. So first defining the class (constructor is called), then register, and after registering calling an init() method on the class.

What do you think?

**Comment by JFusco** [comment]
> Another option might be to instantiate the class, but initialise it externally. So first defining the class (constructor is called), then register, and after registering calling an init() method on the class.

I would suggest that solution for now until I get a chance to improve this a bit. I have some ideas on how to handle the situation, just need the time to implement!

If you have time to submit a PR, I'd love to review it and see if it will work.

Thanks
